/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sleepysp.rsgreetingcard;

import org.junit.Test;

public class AppTest {
    @Test 
    public void testAppHasAGreeting() {
    }
}
