/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sleepysp.rsgreetingcard;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import org.apache.log4j.Logger;

public class App {
    
    private static final Logger logger = Logger.getLogger(App.class);
    
    private JFrame mainFrame = null;
    
    private static App app = null;
    
    public static App get() {
        if (app == null) {
            app = new App();
        }
        return app;
    }
    

    // Public API *********************************************************    
    
    protected synchronized JFrame getMainFrame() {
        if (mainFrame == null) {
            AppUtils.updateUIFonts();
            
            final MainPanel panel = new MainPanel();
            
            final JFrame frame = new JFrame("Ryosan Greeting Cards");
            frame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    int opt = JOptionPane.showConfirmDialog(frame,
                        "Confirm Close?", "Window Closing", JOptionPane.YES_NO_OPTION);
                    
                    if (opt == JOptionPane.YES_OPTION) {
                        System.exit(0);
                    }
                }
            });
            
            
            frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frame.setContentPane(panel);
            frame.pack();
            
            
            mainFrame = frame;
        }
        return mainFrame;
    }

    public void start() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    String sysLaf = UIManager.getSystemLookAndFeelClassName();
                    UIManager.setLookAndFeel(sysLaf);
                }
                catch (Exception ex) {
                    logger.info("Unable to set sys look-and-feel. Ex: " + ex, ex);
                }
                
                
                final JFrame frame = getMainFrame();
                frame.setVisible(true);                
            }
        });        
    }
    
    

}
